CREATE TABLE `wvp_user`
(
    `id`          int                                     NOT NULL AUTO_INCREMENT COMMENT '主键,自增',
    `name`        varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '姓名',
    `nickname`    varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '昵称',
    `sex`         int                                     NOT NULL COMMENT '性别（0、男 1、女）',
    `age`         int                                     NOT NULL COMMENT '年龄',
    `create_time` datetime                                NOT NULL COMMENT '创建时间',
    `update_time` datetime                                NOT NULL COMMENT '更新时间',
    `deleted`     int                                     NOT NULL DEFAULT '0' COMMENT '删除标识（0、逻辑删除 1、物理删除）',
    `version`     int                                     NOT NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';

CREATE TABLE `wvp_media_server`
(
    `id`                  int                                                           NOT NULL AUTO_INCREMENT COMMENT '主键,自增',
    `media_server_id`     varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '流媒体服务器id',
    `secret`              varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '流媒体服务器secret',
    `ip`                  varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '流媒体服务器ip',
    `stream_ip`           varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    `sdp_ip`              varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    `hook_ip`             varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
    `http_port`           int                                                           NOT NULL,
    `http_ssl_port`       int                                                           NOT NULL,
    `rtsp_port`           int                                                           NOT NULL,
    `rtsp_ssl_port`       int                                                           NOT NULL,
    `rtmp_port`           int                                                           NOT NULL,
    `rtmp_ssl_port`       int                                                           NOT NULL,
    `rtp_enable`          tinyint(1) NOT NULL DEFAULT true,
    `rtp_port_range`      varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci  NOT NULL,
    `rtp_proxy_port`      int                                                           NOT NULL,
    `hook_alive_time`     datetime                                                               DEFAULT NULL COMMENT '心跳时间',
    `hook_alive_interval` int                                                           NOT NULL COMMENT '心跳间隔时间（秒）',
    `status`              tinyint(1) NOT NULL DEFAULT true COMMENT '是否在线',
    `default_server`      tinyint(1) NOT NULL DEFAULT true COMMENT '是否默认服务器',
    `create_time`         datetime                                                      NOT NULL COMMENT '创建时间',
    `update_time`         datetime                                                      NOT NULL COMMENT '更新时间',
    `deleted`             int                                                           NOT NULL DEFAULT '0' COMMENT '删除标识（0、逻辑删除 1、物理删除）',
    `version`             int                                                           NOT NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='流媒体服务表';

CREATE TABLE `wvp_device`
(
    `id`                  int                                                           NOT NULL AUTO_INCREMENT COMMENT '主键,自增',
    `device_id`           varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '设备id',
    `ip`                  varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '设备ip',
    `port`                int                                                           NOT NULL COMMENT '设备端口',
    `address`             varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '设备地址',
    `name`                varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '设备名称',
    `manufacturer`        varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '生产厂商',
    `model`               varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '型号',
    `firmware`            varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '固件版本',
    `channels`            int                                                                    DEFAULT NULL COMMENT '通道数',
    `transport`           varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '传输协议（UDP/TCP）',
    `streamMode`          varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '数据流传输模式（UDP/TCP-ACTIVE/TCP-PASSIVE）',
    `status`              tinyint(1) NOT NULL DEFAULT true COMMENT '是否在线',
    `media_server_id`     varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '流媒体服务器id',
    `register_time`       datetime                                                      NOT NULL COMMENT '注册时间',
    `expires`             int                                                           NOT NULL COMMENT '注册有效期',
    `keep_alive_time`     datetime                                                               DEFAULT NULL COMMENT '心跳时间',
    `keep_alive_interval` int                                                           NOT NULL COMMENT '心跳间隔',
    `charset`             varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '字符集（UTF-8/GB2312）',
    `password`            varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '设备密码',
    `primaryStream`       tinyint(1) NOT NULL DEFAULT false COMMENT '主码流',
    `ssrcCheck`           tinyint(1) NOT NULL DEFAULT false COMMENT 'SSRC校验',
    `asMessageChannel`    tinyint(1) NOT NULL DEFAULT false COMMENT '作为消息通道',
    `create_time`         datetime                                                      NOT NULL COMMENT '创建时间',
    `update_time`         datetime                                                      NOT NULL COMMENT '更新时间',
    `deleted`             int                                                           NOT NULL DEFAULT '0' COMMENT '删除标识（0、逻辑删除 1、物理删除）',
    `version`             int                                                           NOT NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='设备表';

CREATE TABLE `wvp_device_channel`
(
    `id`                int                                                           NOT NULL AUTO_INCREMENT COMMENT '主键,自增',
    `device_id`         varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '设备id',
    `channel_id`        varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '通道id',
    `name`              varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '通道名称',
    `manufacturer`      varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '设备厂商',
    `model`             varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '设备型号',
    `owner`             varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '设备归属',
    `civil_code`        varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '行政区域',
    `business_group_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '虚拟组织所属的业务分组ID,业务分组根据特定的业务需求制定,一个业务分组包含一组特定的虚拟组织',
    `parent_id`         varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '父设备/区域/系统ID',
    `register_way`      int                                                                    default 1 DEFAULT NULL COMMENT '注册方式（1、符合IETFRFC3261标准的认证注册模式 2、基于口令的双向认证注册模式 3、基于数字证书的双向认证注册模式）',
    `secrecy`           int                                                                    default 0 DEFAULT NULL COMMENT '保密属性（0、不涉密 1、涉密）',
    `address`           varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '安装地址',
    `parental`          int                                                                    DEFAULT NULL COMMENT '是否有子设备（1、有 0、没有）',
    `block`             varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '警区',
    `safety_way`        int                                                                    default 0 COMMENT '信令安全模式（0、不采用2、S/MIME签名方式 3、S/MIME加密签名同时采用方式 4、数字摘要方式）',
    `cert_num`          varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '证书序列号',
    `certifiable`       int                                                                    DEFAULT 0 COMMENT '证书有效标识（0、无效 1、有效）',
    `err_code`          int                                                                    DEFAULT NULL COMMENT '证书无效原因码',
    `end_time`          varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '证书终止有效期',
    `ip_address`        varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT 'IP地址',
    `port`              int                                                                    DEFAULT NULL COMMENT '端口号',
    `password`          varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '密码',
    `ptz_type`          int                                                                    DEFAULT 0 COMMENT '云台类型',
    `status`            tinyint(1) NOT NULL DEFAULT true COMMENT '是否在线',
    `longitude`         double                                                                 DEFAULT NULL COMMENT '经度',
    `latitude`          double                                                                 DEFAULT NULL COMMENT '经度',
    `stream_id`         varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '流id,存在表示正在直播',
    `has_audio`         tinyint(1) NOT NULL COMMENT '是否含有音频',
    `sub_count`         int                                                                    DEFAULT 0 COMMENT '子设备数',
    `longitude_gcj02`   double                                                                 DEFAULT NULL COMMENT 'GCJ02坐标系经度',
    `latitude_gcj02`    double                                                                 DEFAULT NULL COMMENT 'GCJ02坐标系纬度',
    `longitude_wgs84`   double                                                                 DEFAULT NULL COMMENT 'WGS84坐标系经度',
    `latitude_wgs84`    double                                                                 DEFAULT NULL COMMENT 'WGS84坐标系纬度',
    `group_id`          varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci          DEFAULT NULL COMMENT '分组id',
    `gpsTime`           datetime                                                               DEFAULT NULL COMMENT 'GPS更新时间',
    `create_time`       datetime                                                      NOT NULL COMMENT '创建时间',
    `update_time`       datetime                                                      NOT NULL COMMENT '更新时间',
    `deleted`           int                                                           NOT NULL DEFAULT '0' COMMENT '删除标识（0、逻辑删除 1、物理删除）',
    `version`           int                                                           NOT NULL DEFAULT '0' COMMENT '版本号',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='设备通道表';